import { coldDamage, custom, hydroRot, leafSpot, lowLight, ncsu, oldLeaves, pests, rootRot, sunburn, thirsty, type PlantProfile } from "./types.js";

const ALOHA_SOIL = "Giá thể tơi xốp, thoát nước tốt: đất hữu cơ, xơ dừa, trấu hun, đá perlite; chậu có lỗ thoát nước.";

export const FOLIAGE_A: PlantProfile[] = [
  {
    id: "kim_tien",
    nameVi: "Kim tiền",
    aliases: ["kim tiền", "kim phát tài", "cây tiền", "zz plant"],
    scientific: "Zamioculcas zamiifolia",
    match: { species: ["Zamioculcas zamiifolia"], genera: ["Zamioculcas"] },
    group: "kieng_la",
    basics: {
      lightLevel: "tan_xa",
      light: "Ánh sáng tán xạ tự nhiên hoặc đèn văn phòng; chịu được chỗ thiếu sáng. Tránh nắng gắt chiếu thẳng lâu làm cháy lá.",
      water: "Tưới 7–10 ngày/lần, chỉ tưới khi đất trong chậu đã khô hoàn toàn. Không để nước đọng đáy chậu.",
      soil: ALOHA_SOIL,
      toxic: "Độc mức trung bình (tinh thể canxi oxalat): ăn nhiều lá có thể gây nôn, tiêu chảy. Để xa trẻ nhỏ, chó mèo.",
      note: "Cây giữ nước tốt nên tưới ít còn hơn tưới nhiều. Cắm que tăm sâu 3–5cm: que còn ẩm thì chưa tưới.",
    },
    alohaDoc: "Kim Tiền Thịnh Vượng, Kim Tiền Tài Lộc, Kim Tiền Phát Tài",
    problems: [
      rootRot({
        signs: "Cuống lá vàng từ gốc lên, gốc thân mềm nhũn hoặc thâm đen, đất ẩm lâu ngày; lá rụng khi chạm nhẹ.",
        dry: "đất trong chậu đã khô hoàn toàn (cắm que sâu 3–5cm, rút lên thấy khô)",
        why: "Kim tiền trữ nước trong củ dưới đất nên không chịu được đất ướt lâu. Tưới thường xuyên làm củ và rễ thối, cuống lá vàng rồi gãy gục từ gốc.",
        severity: "nang",
      }),
      sunburn({
        signs: "Lá có mảng vàng nhạt hoặc nâu khô loang lổ ở mặt lá hướng ra nắng, thường sau khi để ra ban công.",
        light: "Đặt chỗ có ánh sáng tán xạ hoặc đèn văn phòng, không để nắng gắt chiếu thẳng.",
      }),
      pests({ kinds: ["rep_vay"] }),
    ],
    source: ncsu("zamioculcas-zamiifolia", "Zamioculcas zamiifolia"),
    reviewed: false,
  },
  {
    id: "luoi_ho",
    nameVi: "Lưỡi hổ",
    aliases: ["lưỡi hổ", "lưỡi cọp", "hổ vĩ", "ngà voi", "lưỡi hổ búp sen", "sansevieria"],
    scientific: "Dracaena trifasciata (Sansevieria)",
    match: {
      species: ["Dracaena trifasciata", "Sansevieria trifasciata", "Dracaena angolensis", "Sansevieria cylindrica", "Dracaena hanningtonii"],
      genera: ["Sansevieria"],
    },
    group: "kieng_la",
    basics: {
      lightLevel: "it_sang",
      light: "Sống khoẻ ở chỗ thiếu sáng hoặc dưới đèn văn phòng. Mỗi tuần cho hứng nắng nhẹ buổi sáng (7–9h) 1 lần để lá lên màu đẹp.",
      water: "Tưới 5–7 ngày/lần, chỉ khi đất đã khô ráo hoàn toàn. Tránh để nước đọng.",
      soil: "Đất thoát nước tốt; chậu có lỗ thoát nước.",
      toxic: "Độc nhẹ (saponin): chó mèo ăn phải có thể nôn, tiêu chảy, chảy dãi; nhựa có thể gây ngứa da. Để xa trẻ nhỏ, thú cưng.",
      note: "Lá tích nước tốt nên tưới nhiều dễ úng rễ. Chịu được không khí khô; trời mát hoặc phòng máy lạnh thì tưới thưa hơn nữa.",
    },
    alohaDoc: "Lưỡi Hổ Thần Tài, Lưỡi Hổ 12 Con Giáp",
    problems: [
      rootRot({
        signs: "Gốc lá mềm nhũn, chuyển vàng hoặc nâu, có mùi hôi; lá ngã rạp từ gốc dù đất còn ẩm.",
        dry: "đất đã khô ráo hoàn toàn",
        why: "Lưỡi hổ trữ nước trong lá nên rất sợ đất ướt lâu. Úng nước làm gốc lá thối mềm, lá gục xuống từ chân.",
        extraSteps: ["Lá nào đã thối mềm ở chân thì cắt bỏ hẳn; phần lá còn lành phía trên có thể cắt khúc đem giâm."],
        severity: "nang",
      }),
      pests({ kinds: ["rep_sap"] }),
      pests({ kinds: ["nhen_do"] }),
    ],
    source: ncsu("dracaena-trifasciata", "Dracaena trifasciata"),
    reviewed: false,
  },
  {
    id: "kim_ngan",
    nameVi: "Kim ngân",
    aliases: ["kim ngân", "kim ngân bính", "kim ngân nơ", "money tree", "pachira"],
    scientific: "Pachira aquatica / Pachira glabra",
    match: { species: ["Pachira aquatica", "Pachira glabra"], genera: ["Pachira"] },
    group: "kieng_la",
    basics: {
      lightLevel: "tan_xa",
      light: "Ánh sáng tán xạ nhẹ (đèn văn phòng, gần cửa sổ có rèm); không chịu được nắng gắt chiếu thẳng.",
      water: "Tưới 1–2 lần/tuần, chỉ khi mặt đất đã khô hẳn. Tưới quanh mép chậu, tránh xối thẳng lên thân gây đọng nước.",
      soil: ALOHA_SOIL,
      toxic: "Độc nhẹ: mèo nhai lá có thể nôn, tiêu chảy, chảy dãi. Hạt có độc nhưng cây trồng trong nhà hầu như không ra hạt.",
      note: "Phun sương hoặc lau lá định kỳ; bón phân tan chậm 2 tháng/lần, thay hoặc bổ sung giá thể sau 6–8 tháng.",
    },
    alohaDoc: "Kim Ngân Cát Tường, Kim Ngân Hạnh Phúc, Kim Ngân Mini",
    problems: [
      rootRot({
        signs: "Lá vàng rồi rụng hàng loạt, gốc thân mềm, vỏ nhăn hoặc thâm đen ở chân; đất ẩm lâu ngày.",
        dry: "mặt đất đã khô hẳn",
        why: "Kim ngân bán trong chậu thường có nhiều thân bện, gốc phình chứa nước; nước đọng làm rễ và chân thân thối, lá vàng rụng.",
        extraSteps: ["Bóp nhẹ từng thân: thân nào đã mềm hẳn là thối, cần tách bỏ để không lây sang thân khác."],
        severity: "nang",
      }),
      thirsty({
        signs: "Lá héo, khô rồi rụng nhiều; đất trong chậu khô cứng lâu ngày.",
        water: "Tưới 1–2 lần/tuần khi mặt đất đã khô hẳn, không để đất khô cứng lâu ngày.",
      }),
      custom({
        id: "vang_la",
        condition: "thieu_dinh_duong",
        title: "Lá vàng do không khí khô hoặc thiếu dinh dưỡng",
        signs: "Lá vàng dần đều, đất không sũng nước, gốc thân vẫn chắc; cây để lâu trong phòng máy lạnh hoặc lâu chưa bón phân.",
        summary: "Không khí quá khô hoặc cây thiếu dinh dưỡng làm lá vàng. Tăng độ ẩm và bón phân đúng liều là lá mới sẽ xanh lại.",
        why: "Kim ngân vàng lá khi độ ẩm không khí quá thấp (phòng máy lạnh) hoặc đất trồng lâu đã cạn dinh dưỡng.",
        steps: [
          "Ngắt bỏ lá đã vàng hẳn để cây dồn sức nuôi chồi mới.",
          "Phun sương lên lá, để cây xa luồng gió máy lạnh thổi thẳng.",
          "Bón phân tan chậm hoặc phân bón lá cho cây cảnh nội thất, đúng liều trên bao bì.",
        ],
        care: ["Bón phân định kỳ 2 tháng/lần.", "Thay hoặc bổ sung giá thể sau 6–8 tháng."],
        severity: "nhe",
      }),
      sunburn({
        signs: "Mép lá hoặc giữa lá cháy nâu, khô giòn ở phía hướng ra nắng.",
        light: "Đặt chỗ ánh sáng tán xạ nhẹ, không để nắng gắt chiếu thẳng.",
      }),
      pests({ kinds: ["rep", "rep_sap", "rep_vay"] }),
    ],
    source: ncsu("pachira-aquatica", "Pachira aquatica"),
    reviewed: false,
  },
  {
    id: "trau_ba",
    nameVi: "Trầu bà (Epipremnum)",
    aliases: ["trầu bà", "trầu bà vàng", "trầu bà lá xanh", "trầu bà thái", "trầu bà sữa", "trầu bà ngọc", "trầu bà treo", "pothos"],
    scientific: "Epipremnum aureum",
    match: { species: ["Epipremnum aureum", "Epipremnum pinnatum"], genera: ["Epipremnum"] },
    group: "kieng_la",
    basics: {
      lightLevel: "tan_xa",
      light: "Nơi thoáng mát, có ánh sáng tán xạ; mỗi tuần cho hứng nắng nhẹ buổi sáng (7–9h) 1–2 lần. Tránh nắng gắt làm nóng nước, hại rễ.",
      water: "Trồng nước: giữ mực nước ngập khoảng 2/3 bộ rễ, thay nước 1–2 lần/tuần (nước máy để lắng hoặc nước lọc). Trồng đất: tưới khi đất mặt đã khô.",
      soil: "Trồng nước: nhỏ 2–3 giọt dung dịch thuỷ sinh sau mỗi lần thay nước. Trồng đất: đất tơi xốp, thoát nước tốt.",
      toxic: "Độc mức trung bình (tinh thể canxi oxalat): nhai phải gây rát, sưng miệng, chảy dãi, nôn; nhựa có thể gây ngứa da. Để xa trẻ nhỏ, chó mèo.",
      note: "Khi thay nước, rửa nhẹ rễ dưới vòi nước và tỉa bỏ rễ già úa; lau lá bằng khăn ẩm mềm.",
    },
    alohaDoc: "Trầu Bà Lá Xanh Thủy Sinh",
    problems: [
      rootRot({
        signs: "Mép lá thâm đen, nhiều lá vàng cùng lúc, thân gần gốc mềm; đất ẩm lâu.",
        dry: "lớp đất mặt đã khô",
        extraSteps: ["Cắt các ngọn còn khoẻ đem cắm nước để giữ giống, phòng khi phần gốc không cứu được."],
      }),
      hydroRot({
        signs: "Cây trồng nước có rễ nâu đen, nhớt, nước đục hoặc có mùi; lá vàng dần.",
        change: "Thay nước 1–2 lần/tuần, nhỏ 2–3 giọt dung dịch thuỷ sinh sau mỗi lần thay.",
      }),
      lowLight({
        signs: "Dây vươn dài, lá mới nhỏ, vân vàng hoặc trắng nhạt dần thành xanh trơn.",
        light: "chỗ thoáng mát có ánh sáng tán xạ, mỗi tuần hứng nắng nhẹ buổi sáng 1–2 lần",
      }),
      pests({ kinds: ["rep_sap", "rep_vay"] }),
      oldLeaves({
        signs: "Lá già ở phần gốc dây vàng rồi rụng dần, lá tập trung ở đầu dây; ngọn vẫn ra lá khoẻ.",
        extraSteps: ["Cắt bớt dây trơ lá để cây đâm nhánh rậm hơn; đoạn cắt cắm nước sẽ ra rễ."],
      }),
    ],
    source: ncsu("epipremnum-aureum", "Epipremnum aureum"),
    reviewed: false,
  },
  {
    id: "philodendron",
    nameVi: "Trầu bà đế vương / Philodendron",
    aliases: ["đế vương", "trầu bà đế vương", "đế vương kim cương", "trầu bà nhung", "trầu bà micans", "trầu bà chân vịt", "philodendron"],
    scientific: "Philodendron spp.",
    match: { genera: ["Philodendron", "Thaumatophyllum"] },
    group: "kieng_la",
    basics: {
      lightLevel: "tan_xa",
      light: "Ánh sáng tán xạ; ánh sáng nhẹ từ cửa sổ hoặc đèn văn phòng là lý tưởng. Mỗi tuần cho hứng nắng nhẹ buổi sáng (7–9h) 1–2 lần; tránh nắng gắt làm cháy lá.",
      water: "Chỉ tưới khi đất khô ráo nhẹ, khoảng 1–2 lần/tuần, mỗi lần 150–200ml quanh gốc (chậu để bàn). Tránh tưới nhiều gây úng rễ.",
      soil: "Giá thể tơi xốp, nhiều mùn, thoát nước tốt.",
      toxic: "Độc nhẹ (tinh thể canxi oxalat): nhai phải gây sưng rát miệng, chảy dãi, nôn; nhựa có thể gây ngứa da. Để xa trẻ nhỏ, chó mèo.",
      note: "Rất nhạy lạnh: tránh gió máy lạnh thổi thẳng và gió lùa. Lau bụi lá bằng khăn ẩm mềm định kỳ.",
    },
    alohaDoc: "Đế Vương Kim Cương, Đế Vương Tam Phúc, Đế Vương Phát Lộc",
    problems: [
      rootRot({
        signs: "Lá vàng từ dưới lên nhanh, bẹ lá hoặc gốc thân mềm, thâm; đất ẩm lâu.",
        dry: "đất mặt đã khô ráo",
      }),
      sunburn({
        signs: "Mảng lá bạc màu, vàng hoặc nâu khô ở phía lá nhận nắng.",
        light: "Đặt chỗ ánh sáng tán xạ, chỉ hứng nắng nhẹ buổi sáng; không để nắng gắt chiếu thẳng.",
      }),
      coldDamage("Lá có mảng sẫm màu, sũng nước rồi khô nâu, thường ở cây đặt gần máy lạnh hoặc cửa gió."),
      leafSpot({ signs: "Lá có đốm nâu hoặc đen, đôi khi viền vàng, lan dần; hay gặp khi lá ướt lâu, cây để chỗ bí gió." }),
      pests({ kinds: ["rep_sap", "rep_vay", "nhen_do"] }),
    ],
    source: ncsu("philodendron", "Philodendron"),
    reviewed: false,
  },
  {
    id: "monstera",
    nameVi: "Trầu bà lá xẻ (Monstera)",
    aliases: ["monstera", "trầu bà lá xẻ", "trầu bà lỗ"],
    scientific: "Monstera deliciosa / Monstera adansonii",
    match: { genera: ["Monstera"] },
    group: "kieng_la",
    basics: {
      lightLevel: "tan_xa",
      light: "Sáng vừa phải, không để nắng chiếu thẳng; giống lá đốm cần sáng hơn giống lá xanh.",
      water: "Tưới đẫm, rồi đợi khoảng 1/4 đến 1/3 lớp đất phía trên khô mới tưới lại.",
      soil: "Đất thoát nước tốt, giữ ẩm vừa phải.",
      toxic: "Độc nhẹ (tinh thể canxi oxalat): ăn phải gây rát miệng, nôn, khó nuốt; nhựa có thể gây ngứa da. Để xa trẻ nhỏ, chó mèo.",
      note: "Cần cọc chắc để thân không gãy; lau bụi lá thường xuyên. Không khí khô thì đặt chậu trên khay sỏi có nước.",
    },
    alohaDoc: null,
    problems: [
      rootRot({
        signs: "Lá vàng loang (cả lá non), có đốm nâu sũng nước, đất ẩm lâu, có mùi hôi.",
        dry: "khoảng 1/4 đến 1/3 lớp đất phía trên đã khô",
      }),
      sunburn({
        signs: "Lá có mảng vàng nhạt hoặc nâu khô ở phía hướng ra nắng.",
        light: "Đặt chỗ sáng vừa phải, không để nắng chiếu thẳng vào lá.",
      }),
      custom({
        id: "nga_than",
        condition: "khac",
        title: "Thân ngả, gãy vì thiếu cọc đỡ",
        signs: "Thân và cuống lá ngả nghiêng, đổ ra ngoài chậu hoặc có chỗ gập, gãy; rễ khí mọc lơ lửng không có chỗ bám.",
        summary: "Monstera là cây leo, lớn lên cần cọc chắc để đỡ thân. Cắm cọc sớm thì thân không gãy.",
        why: "Thân Monstera nặng dần theo số lá; không có cọc đỡ, thân ngả và dễ gãy ở chỗ gập.",
        steps: [
          "Cắm một cọc chắc (cọc dớn hoặc cọc gỗ) sát gốc, cẩn thận không đâm vào rễ lớn.",
          "Buộc lỏng thân vào cọc bằng dây mềm; hướng rễ khí bám vào cọc.",
          "Đoạn thân đã gãy hẳn thì cắt dưới mắt có rễ khí, đem cắm nước hoặc trồng đất để ra cây mới.",
        ],
        care: ["Nới dây buộc khi thân to ra; nâng cọc cao hơn khi cây lớn."],
        severity: "nhe",
      }),
    ],
    source: ncsu("monstera-deliciosa", "Monstera deliciosa"),
    reviewed: false,
  },
  {
    id: "scindapsus",
    nameVi: "Trầu bà bạc / Trầu tróc bạc",
    aliases: ["trầu bà bạc", "trầu tróc bạc", "trầu bà tróc bạc", "trầu bà mây bạc", "satin pothos"],
    scientific: "Scindapsus pictus",
    match: { species: ["Scindapsus pictus"], genera: ["Scindapsus"] },
    group: "kieng_la",
    basics: {
      lightLevel: "tan_xa",
      light: "Ánh sáng tán xạ sáng; không chịu nắng chiếu thẳng.",
      water: "Giữ đất hơi ẩm, tưới khi lớp đất mặt khô; lá cuộn lại là cây đang khát.",
      soil: "Đất tơi xốp, thoát nước tốt.",
      toxic: "Nguồn xếp vào nhóm gây hại cho chó mèo (không ghi chi tiết). Để xa trẻ nhỏ và thú cưng.",
      note: "Không chịu lạnh: tránh gió máy lạnh thổi thẳng. Bấm ngọn để cây gọn, rậm hơn.",
    },
    alohaDoc: null,
    problems: [
      thirsty({
        signs: "Lá cuộn mép vào trong theo chiều dọc, mềm, hơi rũ; đất khô.",
        water: "Tưới khi lớp đất mặt khô, không đợi lá cuộn mới tưới.",
        why: "Trầu bà bạc cuộn lá lại khi thiếu nước để giảm thoát hơi. Tưới kịp thì lá mở ra lại sau vài giờ.",
      }),
      rootRot({
        signs: "Lá vàng, thân gần gốc thâm mềm, đất ẩm lâu không khô.",
        dry: "lớp đất mặt đã khô",
      }),
      sunburn({
        signs: "Mảng lá bạc trắng hoặc nâu khô ở phía hướng ra nắng.",
        light: "Đặt chỗ ánh sáng tán xạ sáng, không để nắng chiếu thẳng vào lá.",
      }),
      leafSpot({ signs: "Lá có đốm nâu, đen hoặc mảng mốc xám, lan dần; hay gặp khi lá ướt lâu, bí gió." }),
      pests({ kinds: ["rep_vay", "rep_sap", "nhen_do", "bo_tri"] }),
    ],
    source: ncsu("scindapsus-pictus", "Scindapsus pictus"),
    reviewed: false,
  },
  {
    id: "lan_y",
    nameVi: "Lan ý",
    aliases: ["lan ý", "bạch môn", "huệ hoà bình", "peace lily", "spathiphyllum"],
    scientific: "Spathiphyllum spp.",
    match: { genera: ["Spathiphyllum"] },
    group: "kieng_la",
    basics: {
      lightLevel: "it_sang",
      light: "Nơi thoáng mát, chịu được chỗ ít sáng; mỗi tuần cho hứng ánh sáng nhẹ buổi sáng (7–9h) 1–2 lần. Tránh nắng gắt làm nóng nước, hại rễ.",
      water: "Trồng nước: mực nước ngập khoảng 2/3 bộ rễ, không chạm gốc thân; thay nước 1–2 tuần/lần hoặc khi nước đục. Trồng đất: giữ đất ẩm nhưng không sũng.",
      soil: "Trồng nước: nhỏ 2–3 giọt dung dịch thuỷ sinh sau mỗi lần thay nước. Trồng đất: đất nhiều mùn, thoát nước tốt.",
      toxic: "Độc mức trung bình (tinh thể canxi oxalat): ăn lá gây đau rát miệng, chảy dãi, nôn, khó nuốt. Để xa trẻ nhỏ, chó mèo.",
      note: "Bón phân thật loãng; bón nhiều làm cháy chóp lá và rễ. Khi thay nước, rửa nhẹ rễ và tỉa bỏ rễ già úa.",
    },
    alohaDoc: "Lan Ý Thủy Sinh Chậu Vuông",
    problems: [
      custom({
        id: "chay_dau_la",
        condition: "khac",
        title: "Khô đầu lá, mép lá nâu",
        signs: "Chóp lá và mép lá khô nâu thành vệt, phần còn lại của lá vẫn xanh.",
        summary: "Đầu lá khô thường do nắng chiếu thẳng, thiếu nước, không khí khô hoặc bón phân quá nhiều. Cây không nguy hiểm.",
        why: "Lan ý bị khô chóp lá khi gặp nắng trực tiếp, thiếu nước, không khí khô (phòng máy lạnh), hoặc muối khoáng tích tụ do bón phân nhiều.",
        steps: [
          "Cắt bỏ phần đầu lá khô bằng kéo sạch, cắt theo dáng lá cho tự nhiên.",
          "Dời cây khỏi chỗ nắng chiếu thẳng và luồng gió máy lạnh.",
          "Cây trồng nước: thay nước mới, giảm dung dịch dinh dưỡng. Cây trồng đất: tưới đẫm cho nước chảy qua đáy chậu để rửa bớt phân.",
        ],
        care: ["Bón phân thật loãng, ít hơn hướng dẫn trên bao bì.", "Giữ nước hoặc đất ẩm đều, không để khô hẳn."],
        severity: "nhe",
      }),
      hydroRot({
        signs: "Lan ý trồng nước có rễ đen nhớt, nước đục hoặc có mùi, lá vàng dần.",
        change: "Thay nước 1–2 tuần/lần hoặc ngay khi nước đục; nước không ngập tới gốc thân.",
      }),
      rootRot({
        signs: "Lá vàng hàng loạt, gốc bẹ lá nâu mềm, đất ẩm sũng và có mùi; cây rũ dù đất ướt.",
        dry: "đất mặt vừa khô",
        why: "Lan ý thích ẩm nhưng không chịu được đất sũng nước. Khi rễ đã thối, cây rũ dù đất ướt vì rễ không hút nước được nữa.",
      }),
      coldDamage("Lá có mảng sẫm màu, sũng nước rồi khô nâu; cây chậm lớn khi để gần máy lạnh hoặc cửa gió."),
      pests({ kinds: ["rep_sap"] }),
    ],
    source: ncsu("spathiphyllum", "Spathiphyllum"),
    reviewed: false,
  },
];
