import {
  NO_TOXIC_DATA,
  custom,
  fungusGnats,
  leafSpot,
  ncsu,
  oldLeaves,
  pests,
  powderyMildew,
  rootRot,
  sunburn,
  type PlantProfile,
} from "./types.js";

export const FOLIAGE_C: PlantProfile[] = [
  {
    id: "hong_mon",
    nameVi: "Hồng môn",
    aliases: ["hồng môn", "vân môn", "môn đỏ", "anthurium"],
    scientific: "Anthurium andraeanum",
    match: { genera: ["Anthurium"] },
    group: "kieng_la",
    basics: {
      lightLevel: "tan_xa",
      light: "Ánh sáng tán xạ sáng; nắng chiếu thẳng làm cháy lá.",
      water: "Tưới khi lớp đất mặt khô khoảng 2–3cm (một đốt ngón tay).",
      soil: "Đất ẩm nhưng thoát nước tốt.",
      toxic: "Độc nhẹ (tinh thể canxi oxalat): nhai phải gây chảy dãi, đau sưng miệng, nôn; nhựa dính da, mắt gây đỏ rát. Để xa trẻ nhỏ, chó mèo.",
      note: "Thích không khí ẩm, không chịu gió lạnh; bón phân loãng thường xuyên khi cây đang lớn để ra hoa đều.",
    },
    alohaDoc: null,
    problems: [
      custom({
        id: "khong_hoa",
        condition: "thieu_sang",
        title: "Ít hoặc không ra hoa",
        signs: "Cây xanh tốt nhưng lâu không ra hoa mới, hoặc hoa nhỏ, nhạt màu.",
        summary: "Thường do thiếu sáng hoặc thiếu dinh dưỡng. Tăng ánh sáng và bón phân đều là hoa ra lại.",
        why: "Hồng môn cần ánh sáng tán xạ sáng và đủ dinh dưỡng để ra hoa; thiếu một trong hai thì cây chỉ ra lá.",
        steps: [
          "Dời cây tới chỗ sáng có ánh sáng tán xạ, không có nắng chiếu thẳng.",
          "Bón phân loãng cho cây ra hoa theo hướng dẫn trên bao bì.",
          "Cắt cuống hoa đã tàn sát gốc để cây dồn sức ra hoa mới.",
        ],
        care: ["Bón phân loãng định kỳ trong mùa cây đang lớn."],
        severity: "nhe",
      }),
      rootRot({
        signs: "Lá vàng, rễ trên mặt chậu nâu nhũn; đất ẩm lâu, thoát nước kém.",
        dry: "lớp đất mặt khô khoảng 2–3cm",
      }),
      leafSpot({ signs: "Lá có đốm nâu hoặc đen, viền vàng, lan dần; hay gặp khi lá ướt lâu hoặc cây để chỗ bí gió." }),
      sunburn({
        signs: "Lá có mảng vàng nhạt hoặc nâu khô ở phía hướng nắng.",
        light: "Đặt chỗ ánh sáng tán xạ sáng, không có nắng chiếu thẳng vào lá.",
      }),
      pests({ kinds: ["rep", "nhen_do", "rep_sap", "rep_vay"] }),
    ],
    source: ncsu("anthurium-andraeanum", "Anthurium andraeanum"),
    reviewed: false,
  },
  {
    id: "truong_sinh",
    nameVi: "Trường sinh (Peperomia)",
    aliases: ["trường sinh", "trường sinh cẩm thạch", "hạt dưa", "peperomia"],
    scientific: "Peperomia spp.",
    match: { genera: ["Peperomia"] },
    group: "kieng_la",
    basics: {
      lightLevel: "tan_xa",
      light: "Nơi thoáng mát, có ánh sáng tán xạ; tránh nắng trực tiếp gay gắt chiếu vào lá.",
      water: "Tưới đều quanh gốc, chỉ khi đất bắt đầu khô ráo (khoảng 2–3 ngày/lần tuỳ độ ẩm). Tránh tưới quá nhiều gây úng.",
      soil: "Đất tơi, trộn cát, thoát nước tốt.",
      toxic: NO_TOXIC_DATA,
      note: "Tưới vào gốc, tránh làm ướt lá để phòng đốm lá; lau bụi lá bằng khăn ẩm hoặc xịt sương nhẹ.",
    },
    alohaDoc: "Trường Sinh Đại Lộc",
    problems: [
      rootRot({
        signs: "Lá vàng hoặc quăn lại, mềm rũ; thân gần gốc thâm nhũn; đất ẩm lâu.",
        dry: "đất bắt đầu khô ráo (cắm que sâu 3–5cm thấy khô)",
        why: "Trường sinh có lá và thân mọng nước, rễ nhỏ, nên rất dễ thối khi tưới nhiều. Lá vàng, quăn là dấu hiệu tưới quá tay.",
        extraSteps: ["Cắt các ngọn còn khoẻ đem giâm để giữ giống, phòng khi gốc không cứu được."],
        severity: "nang",
      }),
      leafSpot({ signs: "Lá có đốm nâu hoặc đen lan dần, hay gặp khi tưới ướt lá." }),
      sunburn({
        signs: "Lá có mảng vàng nhạt hoặc nâu khô ở phía hướng nắng.",
        light: "Đặt chỗ ánh sáng tán xạ, không để nắng gắt chiếu vào lá.",
      }),
      pests({ kinds: ["rep_sap", "nhen_do", "rep", "rep_phan"] }),
      fungusGnats(),
    ],
    source: ncsu("peperomia", "Peperomia"),
    reviewed: false,
  },
  {
    id: "duong_xi",
    nameVi: "Dương xỉ",
    aliases: ["dương xỉ", "dương xỉ lá xoăn", "dương xỉ lá nhuyễn", "dương xỉ tai thỏ", "tổ chim", "tổ quạ", "fern"],
    scientific: "Nephrolepis, Davallia, Asplenium, Pteris",
    match: { genera: ["Nephrolepis", "Davallia", "Asplenium", "Pteris"] },
    group: "kieng_la",
    basics: {
      lightLevel: "tan_xa",
      light: "Ánh sáng tán xạ sáng hoặc bóng râm; tránh nắng chiếu thẳng.",
      water: "Giữ đất luôn ẩm, không bao giờ để khô hẳn; trời lạnh giảm tưới vì tưới nhiều dễ thối rễ.",
      soil: "Đất thoát nước tốt.",
      toxic: NO_TOXIC_DATA,
      note: "Cần không khí ẩm: đặt chậu trên khay sỏi có nước. Chấm nâu xếp hàng dưới mặt lá là bào tử, không phải sâu bệnh.",
    },
    alohaDoc: null,
    problems: [
      custom({
        id: "kho_la",
        condition: "thieu_nuoc",
        title: "Lá khô giòn, rụng lá chét",
        signs: "Lá chuyển nâu, khô giòn từ mép hoặc từ trong bụi, lá chét nhỏ rụng lả tả; đất khô hoặc không khí khô.",
        summary: "Dương xỉ đang thiếu nước hoặc không khí quá khô. Lá đã khô không hồi lại, nhưng bụi sẽ ra lá mới nếu giữ ẩm đều.",
        why: "Dương xỉ cần đất luôn ẩm và không khí ẩm. Để đất khô hoặc đặt trong phòng máy lạnh là lá khô giòn nhanh.",
        steps: [
          "Tưới đẫm ngay, nếu đất khô cứng thì ngâm đáy chậu vào thau nước 15–20 phút.",
          "Cắt bỏ các lá đã khô sát gốc cho bụi thông thoáng.",
          "Dời cây xa máy lạnh, quạt; đặt chậu trên khay sỏi có nước để tăng độ ẩm.",
        ],
        care: ["Giữ đất luôn ẩm, không để khô hẳn.", "Đặt chậu trên khay sỏi có nước để tăng độ ẩm không khí."],
        severity: "chu_y",
      }),
      rootRot({
        signs: "Lá vàng úa từ gốc, gốc bụi đen nhũn, đất sũng nước có mùi; thường khi trời lạnh.",
        dry: "đất mặt vừa se khô (không để khô hẳn)",
        why: "Dương xỉ thích ẩm nhưng khi trời lạnh cây hút ít nước; tưới nhiều lúc này làm gốc bụi thối.",
      }),
      pests({
        kinds: ["rep_vay", "nhen_do"],
        why: "Rệp vảy và nhện đỏ hay xuất hiện trên dương xỉ khi không khí quá khô.",
        extraCare: ["Giữ không khí quanh cây ẩm để phòng nhện đỏ."],
      }),
      custom({
        id: "bao_tu",
        condition: "khac",
        title: "Chấm nâu xếp hàng dưới mặt lá (bào tử, bình thường)",
        signs: "Mặt dưới lá có các chấm nhỏ màu nâu hoặc đen xếp thành hàng đều nhau dọc gân hoặc mép lá; lá vẫn xanh.",
        summary: "Đây là túi bào tử để dương xỉ sinh sản, không phải sâu bệnh.",
        why: "Dương xỉ sinh sản bằng bào tử nằm ở mặt dưới lá. Chấm bào tử xếp đều, cứng, không bò; rệp vảy thì nằm lộn xộn và cạo ra được.",
        steps: ["Không cần xử lý, không xịt thuốc.", "Nếu chấm nằm lộn xộn, cạo ra được và lá vàng quanh đó thì có thể là rệp vảy: gửi ảnh cận để kiểm tra lại."],
        care: ["Giữ cách chăm bình thường."],
        severity: "nhe",
      }),
    ],
    source: ncsu("nephrolepis-exaltata", "Nephrolepis exaltata"),
    reviewed: false,
  },
  {
    id: "cau",
    nameVi: "Cau cảnh (cau tiểu trâm, cau Nhật, kè)",
    aliases: ["cau tiểu trâm", "cau", "cau đài loan", "cau nhật", "kè nhật", "cọ nhật", "cau vàng", "mật cật", "palm"],
    scientific: "Chamaedorea elegans và các loài cau cảnh",
    match: { genera: ["Chamaedorea", "Dypsis", "Rhapis", "Howea", "Livistona", "Phoenix"], families: ["Arecaceae"] },
    group: "kieng_la",
    basics: {
      lightLevel: "tan_xa",
      light: "Ưa ánh sáng tán xạ, đặt nơi thoáng mát; tránh nắng gắt chiếu thẳng vào lá. Chịu được chỗ ít sáng.",
      water: "Tưới khi lớp đất bề mặt đã khô; tránh tưới quá nhiều gây úng, thối rễ.",
      soil: "Đất nhiều mùn, thoát nước tốt.",
      toxic: "Cau tiểu trâm không gây hại cho thú cưng; riêng nước quả (hiếm có ở cây trồng trong nhà) có thể gây ngứa da.",
      note: "Tránh gió lạnh ở cửa sổ, cửa gió máy lạnh. Lau lá bằng khăn ẩm mềm định kỳ.",
    },
    alohaDoc: "Vườn Cau Tiểu Trâm",
    problems: [
      rootRot({
        signs: "Lá vàng úa cả bụi, gốc thân thâm mềm, đất sũng nước.",
        dry: "lớp đất bề mặt đã khô",
      }),
      pests({
        kinds: ["nhen_do"],
        why: "Nhện đỏ rất hay gặp trên cau để trong phòng khô; chúng hút nhựa làm lá lốm đốm vàng.",
        extraCare: ["Phun sương và lau lá bằng khăn ẩm định kỳ để phòng nhện đỏ."],
      }),
      pests({ kinds: ["rep_sap"] }),
    ],
    source: ncsu("chamaedorea-elegans", "Chamaedorea elegans"),
    reviewed: false,
  },
  {
    id: "thuong_xuan",
    nameVi: "Thường xuân",
    aliases: ["thường xuân", "dây thường xuân", "ivy", "hedera"],
    scientific: "Hedera helix",
    match: { genera: ["Hedera"] },
    group: "kieng_la",
    basics: {
      lightLevel: "tan_xa",
      light: "Thích nghi rộng, từ bóng râm tới nắng; trồng trong nhà nên để chỗ sáng có ánh sáng tán xạ.",
      water: "Giữ đất hơi ẩm, đất phải thoát nước tốt.",
      soil: "Đất thoát nước tốt.",
      toxic: "Độc mức trung bình (saponin): nhựa gây ngứa đỏ, phồng rộp da; ăn lá có thể gây nôn, đau bụng, tiêu chảy. Đeo găng khi cắt tỉa, để xa trẻ nhỏ và thú cưng.",
      note: "Nên trồng chậu, không trồng xuống đất vườn: cây lan rất mạnh, leo bám làm hại cây khác và tường nhà.",
    },
    alohaDoc: null,
    problems: [
      pests({ kinds: ["rep", "rep_sap", "nhen_do", "rep_vay"] }),
      custom({
        id: "sau_an_la",
        condition: "sau_hai",
        title: "Bị sâu ăn lá",
        signs: "Lá bị gặm thủng lỗ hoặc khuyết mép, có phân sâu nhỏ màu đen trên lá; có thể thấy sâu xanh nằm dọc gân lá.",
        summary: "Sâu đang ăn lá. Bắt sâu sớm là cây ra lá mới bình thường.",
        why: "Sâu non của bướm, ngài ăn lá non và lá bánh tẻ, thường nấp ở mặt dưới lá.",
        steps: [
          "Lật mặt dưới lá, bắt sâu bằng tay (đeo găng vì nhựa thường xuân gây ngứa).",
          "Ngắt bỏ lá bị ăn nặng.",
          "Bị nhiều thì dùng chế phẩm trừ sâu sinh học có bán tại Aloha, pha đúng hướng dẫn trên bao bì.",
        ],
        care: ["Mỗi tuần lật xem mặt dưới lá để phát hiện sâu sớm."],
        severity: "nhe",
      }),
      leafSpot({ signs: "Lá có đốm nâu hoặc đen, có thể viền vàng hoặc sũng nước, lan dần." }),
      powderyMildew({ signs: "Mặt lá có lớp bột trắng như phấn, lá non quăn lại." }),
    ],
    source: ncsu("hedera-helix", "Hedera helix"),
    reviewed: false,
  },
  {
    id: "ficus",
    nameVi: "Đa / Si / Bàng Singapore (Ficus)",
    aliases: ["đa búp", "đa búp đỏ", "đa lộc", "cây si", "bàng singapore", "bàng sing", "ficus"],
    scientific: "Ficus elastica, Ficus lyrata, Ficus microcarpa…",
    match: { genera: ["Ficus"] },
    group: "bonsai_cay_go",
    basics: {
      lightLevel: "tan_xa",
      light: "Ánh sáng tán xạ sáng hoặc nắng một phần trong ngày; che nắng buổi chiều.",
      water: "Tưới đều nhưng tránh tưới quá nhiều; khi cây ngưng lớn (mùa lạnh) thì giảm tưới hẳn.",
      soil: "Đất trồng chậu có đất thịt, thoát nước tốt.",
      toxic: "Nguồn xếp vào nhóm gây hại cho chó mèo (không ghi chi tiết); lá bị cắt sẽ chảy nhựa trắng. Để xa trẻ nhỏ và thú cưng.",
      note: "Cây thích ở yên một chỗ, không chịu gió lùa và lạnh. Lau bụi lá bằng khăn hoặc mút mềm ẩm.",
    },
    alohaDoc: null,
    problems: [
      custom({
        id: "rung_la",
        condition: "khac",
        title: "Rụng lá do tưới nhiều, lạnh hoặc gió lùa",
        signs: "Lá xanh hoặc vàng rụng nhiều; cây vừa bị tưới nhiều, đặt gần máy lạnh, cửa gió hoặc trời trở lạnh.",
        summary: "Cây họ đa rụng lá khi bị tưới quá nhiều, lạnh hoặc gió lùa. Giữ ổn định thì cây sẽ ra lá mới.",
        why: "Ficus phản ứng với đất quá ướt, nhiệt độ hạ và gió lùa bằng cách rụng lá.",
        steps: [
          "Kiểm tra đất: nếu còn ẩm thì ngưng tưới cho tới khi đất mặt khô.",
          "Dời cây khỏi luồng gió máy lạnh và cửa gió; giữ cố định một chỗ.",
          "Không thay chậu, không bón phân trong lúc cây rụng lá.",
        ],
        care: ["Hạn chế dời chỗ; tưới đều, không tưới quá nhiều."],
        severity: "chu_y",
      }),
      oldLeaves({ signs: "Một vài lá dưới cùng vàng rồi rụng, lá ở ngọn vẫn xanh khoẻ." }),
      pests({ kinds: ["rep_sap", "rep_vay", "nhen_do"] }),
    ],
    source: ncsu("ficus-elastica", "Ficus elastica"),
    reviewed: false,
  },
];
