import { NO_TOXIC_DATA, custom, fungusGnats, hydroRot, leafSpot, lowLight, ncsu, pests, rootRot, sunburn, thirsty, type PlantProfile } from "./types.js";

const ALOHA_SOIL = "Giá thể tơi xốp, thoát nước tốt: đất hữu cơ, xơ dừa, trấu hun, đá perlite.";
const SAPONIN = "Độc nhẹ (saponin): chó mèo ăn phải có thể nôn, chảy dãi, bỏ ăn; nhựa có thể gây ngứa da. Để xa trẻ nhỏ, chó mèo.";

const dryAirTips = (o: { id: string; title: string; signs: string; why: string; extraSteps?: string[]; care?: string[] }) =>
  custom({
    id: o.id,
    condition: "khac",
    title: o.title,
    signs: o.signs,
    summary: "Chóp hoặc mép lá khô do không khí khô hoặc nước tưới. Phần đã khô không xanh lại nhưng cây không nguy hiểm.",
    why: o.why,
    steps: [
      "Cắt bỏ phần khô bằng kéo sạch, cắt theo dáng lá, không cắt vào phần xanh.",
      "Để cây xa luồng gió máy lạnh, quạt và cửa gió.",
      ...(o.extraSteps ?? ["Phun sương quanh cây hoặc đặt chậu trên khay sỏi có nước để tăng độ ẩm."]),
    ],
    care: o.care ?? ["Giữ độ ẩm không khí quanh cây, tránh gió lùa."],
    severity: "nhe",
  });

export const FOLIAGE_B: PlantProfile[] = [
  {
    id: "van_loc",
    nameVi: "Vạn lộc / Ngọc ngân (Aglaonema)",
    aliases: ["vạn lộc", "vạn lộc son", "ngọc ngân", "bạch mã hoàng tử", "phú quý", "đại phú gia", "huyết rồng", "aglaonema"],
    scientific: "Aglaonema spp.",
    match: { genera: ["Aglaonema"] },
    group: "kieng_la",
    basics: {
      lightLevel: "tan_xa",
      light: "Ánh sáng tán xạ: cạnh cửa sổ có rèm che hoặc dưới đèn văn phòng. Tránh nắng gắt chiếu thẳng làm cháy lá.",
      water: "Tưới khi đất mặt se khô, giữ độ ẩm đều; tránh tưới quá nhiều gây úng, thối rễ.",
      soil: "Đất tơi xốp, thoát nước tốt.",
      toxic: "Độc nhẹ (tinh thể canxi oxalat): nhai phải gây rát, sưng miệng, chảy dãi, nôn; nhựa có thể gây ngứa da. Để xa trẻ nhỏ, chó mèo.",
      note: "Không tưới nước lạnh; tránh gió lùa, gió máy lạnh. Lau lá bằng khăn mềm ẩm định kỳ.",
    },
    alohaDoc: "Thành phẩm Vạn Lộc để bàn",
    problems: [
      rootRot({
        signs: "Lá vàng từ dưới lên, gốc thân mềm hoặc thâm, đất ẩm lâu.",
        dry: "đất mặt se khô",
        extraCare: ["Không tưới nước lạnh."],
      }),
      dryAirTips({
        id: "la_nau",
        title: "Lá nâu khô do không khí khô hoặc gió lùa",
        signs: "Mép hoặc mảng lá chuyển nâu khô; cây để chỗ không khí khô, gần máy lạnh hoặc cửa gió.",
        why: "Vạn lộc chuyển nâu lá khi không khí quá khô hoặc đặt chỗ có gió lùa.",
      }),
      pests({ kinds: ["rep", "rep_sap", "nhen_do", "rep_vay"] }),
    ],
    source: ncsu("aglaonema", "Aglaonema"),
    reviewed: false,
  },
  {
    id: "van_nien_thanh",
    nameVi: "Vạn niên thanh (Dieffenbachia)",
    aliases: ["vạn niên thanh", "dieffenbachia"],
    scientific: "Dieffenbachia spp.",
    match: { genera: ["Dieffenbachia"] },
    group: "kieng_la",
    basics: {
      lightLevel: "tan_xa",
      light: "Chỗ sáng vừa, có thể nhận chút nắng nhẹ trong ngày; tránh nắng gắt buổi trưa.",
      water: "Giữ đất hơi ẩm, có thể để đất mặt khô bớt giữa hai lần tưới; không để sũng.",
      soil: "Đất thoát nước tốt.",
      toxic: "Độc mức CAO: nhựa gây bỏng rát, sưng miệng và họng, khó nói, khó nuốt; dính vào mắt có thể tổn thương mắt; có thể gây tử vong cho thú cưng. Để xa trẻ nhỏ và thú cưng.",
      note: "Luôn đeo găng tay khi cắt tỉa hoặc thay chậu; rửa tay sau khi chạm vào nhựa cây.",
    },
    alohaDoc: null,
    problems: [
      rootRot({
        signs: "Thân gần gốc mềm nhũn, vàng hoặc thâm, lá rũ dù đất ẩm.",
        dry: "đất mặt đã khô bớt",
        extraSteps: ["Đeo găng tay khi cắt vì nhựa cây rất độc, gây bỏng rát."],
        severity: "nang",
      }),
      leafSpot({ signs: "Lá có đốm nâu hoặc đen, có thể viền vàng, lan dần sang lá khác." }),
      pests({ kinds: ["nhen_do", "rep_vay", "rep_phan", "rep"], extraSteps: ["Đeo găng tay khi lau lá."] }),
      fungusGnats(),
    ],
    source: ncsu("dieffenbachia-seguine", "Dieffenbachia seguine"),
    reviewed: false,
  },
  {
    id: "phat_tai",
    nameVi: "Phát tài / Thiết mộc lan (Dracaena)",
    aliases: ["phát tài", "thiết mộc lan", "phát tài núi", "trúc bách hợp", "trúc đốm vàng", "phất dủ", "huyết giác", "dracaena"],
    scientific: "Dracaena fragrans và các loài Dracaena khác",
    match: { species: ["Dracaena fragrans", "Dracaena reflexa", "Dracaena marginata", "Dracaena surculosa", "Dracaena deremensis"], genera: ["Dracaena"] },
    group: "kieng_la",
    basics: {
      lightLevel: "tan_xa",
      light: "Ánh sáng tán xạ, sống tốt trong văn phòng máy lạnh; tránh nắng trực tiếp (cây thuỷ sinh dễ nóng nước, hại rễ).",
      water: "Trồng đất: tưới 2–3 lần/tuần khi bề mặt đất khô. Trồng nước: thay nước 7–10 ngày/lần bằng nước máy để qua đêm, nước ngập khoảng 2/3 bộ rễ, không ngập thân.",
      soil: "Trồng đất: giá thể đất hữu cơ, xơ dừa, trấu hun, đá perlite. Trồng nước: nhỏ 2–3 giọt dung dịch thuỷ canh mỗi lần thay nước, không cho quá nhiều.",
      toxic: SAPONIN,
      note: "Phun sương lá buổi sáng, tỉa bỏ lá vàng ở gốc; bón phân tan chậm hoặc hữu cơ 1 tháng/lần.",
    },
    alohaDoc: "Phát Tài Như Ý, Phát Tài Thủy Sinh",
    problems: [
      dryAirTips({
        id: "kho_dau_la",
        title: "Khô chóp lá, mép lá nâu",
        signs: "Chóp lá khô nâu, có thể có viền vàng ngăn cách phần khô và phần xanh; xuất hiện trên nhiều lá.",
        why: "Dracaena nhạy với chất flo và muối khoáng tích tụ trong đất (từ nước máy, phân bón) và với không khí khô; chóp lá là nơi khô trước tiên.",
        extraSteps: ["Tưới bằng nước để qua đêm hoặc nước lọc; phun sương lá buổi sáng."],
        care: ["Mỗi tháng tưới thật đẫm cho nước chảy qua đáy chậu để rửa muối khoáng.", "Bón phân đúng liều, không bón quá nhiều."],
      }),
      rootRot({
        signs: "Lá vàng cả ở ngọn, thân mềm ở gốc hoặc ngọn bị thối nhũn, đất ẩm lâu.",
        dry: "bề mặt đất đã khô",
      }),
      hydroRot({
        signs: "Cây trồng nước có rễ nâu đen, nhớt, nước đục hoặc có mùi; lá vàng dần.",
        change: "Thay nước 7–10 ngày/lần, rửa nhẹ rễ và lòng bình mỗi lần thay.",
      }),
      lowLight({
        signs: "Lá mới hẹp, mỏng và nhạt màu hơn lá cũ; sọc màu mờ đi.",
        light: "chỗ có ánh sáng tán xạ, gần cửa sổ có rèm",
      }),
      pests({ kinds: ["bo_tri", "rep_sap"] }),
    ],
    source: ncsu("dracaena-fragrans", "Dracaena fragrans"),
    reviewed: false,
  },
  {
    id: "truc_phat_tai",
    nameVi: "Trúc phát tài",
    aliases: ["trúc phát tài", "phát tài lộc", "trúc may mắn", "tháp trúc", "lucky bamboo"],
    scientific: "Dracaena sanderiana",
    match: { species: ["Dracaena sanderiana", "Dracaena braunii"] },
    group: "kieng_la",
    basics: {
      lightLevel: "tan_xa",
      light: "Ưa nắng tán xạ (ánh sáng qua rèm, đèn văn phòng); không chịu nắng gắt chiếu thẳng vì dễ cháy lá.",
      water: "Trồng đất: tưới 1–2 lần/tuần, chạm tay thấy mặt giá thể khô hoàn toàn mới tưới. Trồng nước: thay nước mỗi tuần, dùng nước không có clo (nước để qua đêm hoặc nước lọc).",
      soil: ALOHA_SOIL,
      toxic: SAPONIN,
      note: "Phun sương lá hằng ngày cho xanh bóng, sạch bụi; tỉa bỏ lá già, lá vàng ở gốc.",
    },
    alohaDoc: "Trúc Phát Tài thành phẩm, Combo Trúc Phát Tài 3 thân",
    problems: [
      custom({
        id: "vang_than",
        condition: "ung_re",
        title: "Lá vàng, thân thối do tưới nhiều",
        signs: "Lá vàng nhiều, thân chuyển vàng từ dưới lên hoặc mềm nhũn, có mùi; có thể lan sang thân bên cạnh.",
        summary: "Tưới quá nhiều làm lá vàng và thân thối. Thân đã vàng không xanh lại được, cần tách ra ngay để cứu các thân còn lại.",
        why: "Đất hoặc nước quá ẩm, bẩn làm gốc thân thối. Thân trúc đã vàng là phần đó đã chết và có thể lây sang thân khác trong cùng chậu.",
        steps: [
          "Tách thân vàng hoặc thối ra khỏi bó ngay.",
          "Nếu phần ngọn còn xanh, cắt lấy đoạn ngọn khoẻ đem cắm nước riêng cho ra rễ.",
          "Trồng đất: ngưng tưới tới khi mặt giá thể khô hoàn toàn. Trồng nước: rửa sạch bình, sỏi và rễ các thân còn lại, thay nước mới.",
        ],
        care: ["Chỉ tưới khi mặt giá thể khô hoàn toàn.", "Cây trồng nước: thay nước mỗi tuần, không để nước đục hoặc có mùi."],
        severity: "chu_y",
        needHelp: true,
      }),
      dryAirTips({
        id: "kho_chop",
        title: "Khô chóp lá do không khí khô",
        signs: "Chóp lá khô nâu trên nhiều lá, thân vẫn xanh cứng; cây để phòng máy lạnh.",
        why: "Trúc phát tài bị khô chóp lá khi độ ẩm không khí thấp.",
        extraSteps: ["Phun sương lên lá hằng ngày."],
      }),
      hydroRot({
        signs: "Rễ đen nhớt, nước đục hoặc có rêu xanh, có mùi hôi.",
        change: "Thay nước mỗi tuần, dùng nước không có clo (nước để qua đêm hoặc nước lọc).",
      }),
      sunburn({
        signs: "Lá có mảng vàng hoặc nâu khô ở phía hướng ra nắng.",
        light: "Đặt chỗ nắng tán xạ (qua rèm) hoặc dưới đèn văn phòng, không để nắng gắt chiếu thẳng.",
      }),
      pests({ kinds: ["rep_sap", "nhen_do", "rep_vay"] }),
    ],
    source: ncsu("dracaena-sanderiana", "Dracaena sanderiana"),
    reviewed: false,
  },
  {
    id: "hanh_phuc",
    nameVi: "Hạnh phúc",
    aliases: ["hạnh phúc", "cây hạnh phúc", "china doll", "radermachera"],
    scientific: "Radermachera sinica",
    match: { species: ["Radermachera sinica"], genera: ["Radermachera"] },
    group: "kieng_la",
    basics: {
      lightLevel: "tan_xa",
      light: "Ưu tiên ánh sáng tán xạ dịu nhẹ; mỗi tuần cho hứng nắng nhẹ buổi sáng (7–9h) 1–2 lần. Tránh nắng gắt làm cháy lá.",
      water: "Tưới khi đất mặt bắt đầu se khô; phun sương mịn giữ ẩm cho lá. Tránh tưới quá nhiều gây úng, thối rễ.",
      soil: "Đất tơi xốp, thoát nước tốt; chậu phải có lỗ thoát nước.",
      toxic: NO_TOXIC_DATA,
      note: "Rất nhạy khi bị dời chỗ, thay chậu: mua về nên để cố định một chỗ, chưa thay chậu và chưa bón phân cho tới khi cây ra lá mới.",
    },
    alohaDoc: "Hạnh Phúc An Khang, Hạnh Phúc May Mắn",
    problems: [
      custom({
        id: "rung_la",
        condition: "khac",
        title: "Rụng lá sau khi dời chỗ, thay chậu",
        signs: "Lá vàng hoặc còn xanh rụng nhiều sau khi mua về, dời chỗ hoặc thay chậu; đất không quá khô, không quá ướt.",
        summary: "Cây hạnh phúc rất nhạy khi bị dời chỗ. Giữ cây ổn định một chỗ thì cây sẽ ra lá mới.",
        why: "Cây hạnh phúc phản ứng với việc dời chỗ, thay chậu bằng cách rụng lá.",
        steps: [
          "Đặt cây cố định ở chỗ có ánh sáng tán xạ, không dời đi dời lại.",
          "Không thay chậu, không bón phân cho tới khi cây ra lá mới.",
          "Tưới khi đất mặt se khô, không tưới thêm vì nghĩ cây thiếu nước.",
        ],
        care: ["Hạn chế dời chỗ; nếu cần dời thì chọn chỗ có ánh sáng tương tự."],
        severity: "chu_y",
      }),
      rootRot({
        signs: "Lá chuyển đen rồi rụng, kể cả lá non; đất luôn ẩm.",
        dry: "đất mặt bắt đầu se khô",
        why: "Lá đen rồi rụng là dấu hiệu tưới quá nhiều: rễ bị úng, không nuôi được lá.",
      }),
      thirsty({
        signs: "Lá khô, giòn rồi rụng; đất khô.",
        water: "Tưới khi đất mặt bắt đầu se khô, không để đất khô hẳn.",
        why: "Lá khô giòn là dấu hiệu cây thiếu nước; cây hạnh phúc rất nhạy với cả thiếu nước lẫn thừa nước.",
      }),
    ],
    source: {
      name: "University of Illinois Extension – Ask Extension: China Doll (Radermachera sinica)",
      url: "https://web.extension.illinois.edu/askextension/thisQuestion.cfm?AskSiteID=34&catID=31&ThreadID=22787",
    },
    reviewed: false,
  },
  {
    id: "ngu_gia_bi",
    nameVi: "Ngũ gia bì",
    aliases: ["ngũ gia bì", "chân chim", "schefflera"],
    scientific: "Schefflera arboricola (Heptapleurum arboricola)",
    match: { species: ["Schefflera arboricola", "Heptapleurum arboricola"], genera: ["Schefflera", "Heptapleurum"] },
    group: "kieng_la",
    basics: {
      lightLevel: "tan_xa",
      light: "Nơi thoáng mát có ánh sáng tán xạ; tránh nắng gắt buổi trưa chiếu thẳng để lá không bị cháy.",
      water: "Tưới đều quanh gốc khi đất bắt đầu khô. Cây chịu hạn tốt hơn chịu úng nên đất phải thoát nước tốt.",
      soil: "Đất tơi xốp, nhiều mùn, thoát nước tốt.",
      toxic: "Có tinh thể canxi oxalat: chó mèo nhai lá bị rát miệng, chảy dãi, khó nuốt, nôn; nhựa có thể gây ngứa da. Để xa thú cưng.",
      note: "Lau lá bằng khăn mềm ẩm 1–2 lần/tuần cho sạch bụi.",
    },
    alohaDoc: "Combo Ngũ Gia Bì để bàn",
    problems: [
      rootRot({
        signs: "Lá vàng, có đốm đen rồi rụng; đất ẩm lâu, gốc thâm.",
        dry: "đất bắt đầu khô",
        why: "Ngũ gia bì rụng lá khi đất quá ướt: rễ bị úng không nuôi được lá.",
      }),
      thirsty({
        signs: "Lá héo, khô rồi rụng; đất khô cứng lâu ngày.",
        water: "Tưới đều quanh gốc khi đất bắt đầu khô.",
      }),
      sunburn({
        signs: "Lá có mảng vàng nhạt hoặc nâu khô ở phía hướng ra nắng.",
        light: "Đặt chỗ ánh sáng tán xạ, tránh nắng gắt buổi trưa.",
      }),
      pests({ kinds: ["nhen_do"] }),
      pests({ kinds: ["rep_sap", "rep_vay"], why: "Rệp sáp và rệp vảy bám thân, nách lá hút nhựa; trên ngũ gia bì chúng có thể gây hại nặng nếu không xử lý sớm." }),
    ],
    source: ncsu("heptapleurum-arboricola", "Heptapleurum arboricola"),
    reviewed: false,
  },
  {
    id: "duoi_cong",
    nameVi: "Đuôi công (Calathea)",
    aliases: ["đuôi công", "đuôi công táo xanh", "đuôi công tím", "calathea", "maranta"],
    scientific: "Goeppertia (Calathea), Maranta, Ctenanthe, Stromanthe",
    match: { genera: ["Goeppertia", "Calathea", "Maranta", "Ctenanthe", "Stromanthe"] },
    group: "kieng_la",
    basics: {
      lightLevel: "tan_xa",
      light: "Ánh sáng tán xạ hoặc bóng râm sáng; nắng chiếu thẳng làm cháy lá.",
      water: "Giữ đất hơi ẩm đều, không để khô hẳn và không để sũng.",
      soil: "Đất thoát nước tốt, giữ ẩm vừa.",
      toxic: NO_TOXIC_DATA,
      note: "Lá tự khép lại vào buổi tối là bình thường. Cây thích không khí ẩm, không chịu lạnh: tránh gió máy lạnh.",
    },
    alohaDoc: null,
    problems: [
      dryAirTips({
        id: "kho_mep",
        title: "Mép lá nâu do không khí khô",
        signs: "Mép lá và chóp lá khô nâu giòn; cây để phòng máy lạnh hoặc chỗ khô nóng.",
        why: "Đuôi công cần độ ẩm không khí cao; không khí khô làm mép lá khô nâu.",
      }),
      thirsty({
        signs: "Lá cuộn tròn lại hoặc vàng, rũ xuống; đất khô.",
        water: "Giữ đất hơi ẩm đều, tưới khi đất mặt vừa se khô.",
        why: "Đuôi công cuộn lá, vàng lá khi thiếu nước. Lưu ý lá cũng tự khép lại vào buổi tối – đó là bình thường.",
      }),
      rootRot({
        signs: "Thân, cuống lá mềm nhũn, lá rũ; đất sũng nước, thường khi trời lạnh.",
        dry: "đất mặt vừa se khô (không đợi khô hẳn)",
        why: "Tưới quá nhiều, nhất là khi trời lạnh, làm thân và gốc thối.",
      }),
      sunburn({
        signs: "Hoa văn trên lá bạc màu, lá có mảng vàng nâu khô ở phía hướng nắng.",
        light: "Đặt chỗ ánh sáng tán xạ hoặc bóng râm sáng, không có nắng chiếu thẳng.",
      }),
      pests({ kinds: ["rep", "rep_vay", "rep_sap", "nhen_do"] }),
    ],
    source: ncsu("goeppertia", "Goeppertia (Calathea)"),
    reviewed: false,
  },
  {
    id: "mon",
    nameVi: "Môn (Alocasia)",
    aliases: ["cây môn", "môn quan âm", "môn rồng", "môn huyết long", "môn kiểng", "môn trắng", "alocasia"],
    scientific: "Alocasia spp.",
    match: { genera: ["Alocasia", "Colocasia"] },
    group: "kieng_la",
    basics: {
      lightLevel: "tan_xa",
      light: "Chỗ sáng có bóng râm, ánh sáng tán xạ; tránh nắng gắt chiếu thẳng.",
      water: "Tưới đều để đất ẩm nhưng thoát nước tốt; trời lạnh giảm tưới.",
      soil: "Đất tơi xốp, nhiều mùn, hơi chua, thoát nước tốt.",
      toxic: "Độc mức trung bình (tinh thể canxi oxalat): nhai phải gây đau rát môi, miệng, họng, khó nói, buồn nôn; nhựa dính da gây ngứa. Để xa trẻ nhỏ, chó mèo.",
      note: "Cây rất hay bị nhện đỏ: mỗi tuần xem và lau mặt dưới lá.",
    },
    alohaDoc: null,
    problems: [
      rootRot({
        signs: "Cuống lá mềm nhũn, củ ở gốc mềm hoặc thâm, lá vàng; đất ẩm lâu có mùi.",
        dry: "lớp đất mặt khô bớt",
        severity: "nang",
      }),
      pests({
        kinds: ["nhen_do"],
        why: "Môn rất dễ bị nhện đỏ, nhất là khi không khí khô; chúng hút nhựa làm lá lốm đốm rồi xỉn màu.",
        extraCare: ["Lau mặt dưới lá mỗi tuần."],
      }),
      pests({ kinds: ["rep", "rep_sap"] }),
      leafSpot({ signs: "Lá có đốm nâu hoặc đen, viền vàng, lan dần; thường khi tưới nhiều, lá ướt lâu." }),
      thirsty({
        signs: "Lá vàng, rũ, mép lá khô; đất khô.",
        water: "Tưới đều để đất ẩm, không để đất khô hẳn.",
      }),
    ],
    source: ncsu("alocasia", "Alocasia"),
    reviewed: false,
  },
];
