import { BRING, NO_TOXIC_DATA, custom, ncsu, pests, powderyMildew, rootRot, thirsty, type PlantProfile } from "./types.js";

export const WOODY: PlantProfile[] = [
  {
    id: "tung",
    nameVi: "Tùng la hán / Kim giao",
    aliases: ["tùng la hán", "la hán tùng", "kim giao", "thông la hán", "podocarpus"],
    scientific: "Podocarpus macrophyllus / Nageia fleuryi",
    match: { genera: ["Podocarpus", "Nageia"] },
    group: "bonsai_cay_go",
    basics: {
      lightLevel: "sang_manh",
      light: "Nắng đầy đủ tới nắng một phần trong ngày; chịu được bóng râm.",
      water: "Giữ đất hơi ẩm nhưng không để sũng nước; cây chịu hạn khá tốt.",
      soil: "Đất giàu dinh dưỡng, hơi chua, thoát nước tốt.",
      toxic: "Độc nhẹ: ăn phải lá hoặc hạt có thể buồn nôn, nôn, tiêu chảy; trẻ nhỏ dễ ăn nhầm hạt. Để xa trẻ nhỏ và thú cưng.",
      note: "Chịu cắt tỉa tốt nên dễ tạo dáng bonsai, hàng rào.",
    },
    alohaDoc: null,
    problems: [
      rootRot({
        signs: "Lá vàng úa từ trong ra ngoài, rụng nhiều; đất ẩm lâu, gốc thâm.",
        dry: "lớp đất mặt đã khô",
        why: "Tùng la hán chịu được bóng râm nhưng không chịu được đất ướt lâu; úng nước làm rễ thối, lá vàng rụng.",
      }),
      pests({ kinds: ["rep_vay"], why: "Tùng trồng trong nhà hay bị rệp vảy bám cành, gân lá hút nhựa." }),
      custom({
        id: "vang_la_kiem",
        condition: "thieu_dinh_duong",
        title: "Lá vàng nhạt do đất kiềm",
        signs: "Lá non vàng nhạt dần, gân lá có thể vẫn xanh; đất không sũng nước, cây trồng lâu năm chưa thay đất.",
        summary: "Đất bị kiềm làm cây khó hút dinh dưỡng nên lá vàng nhạt. Thay đất hơi chua và bón phân là lá mới sẽ xanh lại.",
        why: "Tùng la hán ưa đất hơi chua; trong đất kiềm cây không hút đủ sắt và vi lượng nên lá vàng nhạt (vàng lá sinh lý).",
        steps: [
          "Kiểm tra đất không bị sũng nước (nếu sũng thì xem mục úng rễ).",
          "Bón phân có vi lượng cho cây cảnh, đúng liều trên bao bì.",
          `Cây trồng lâu năm: thay đất mới giàu mùn, hơi chua, thoát nước tốt. ${BRING}`,
        ],
        care: ["Dùng đất giàu mùn, hơi chua; thay đất định kỳ cho cây trồng chậu."],
        severity: "nhe",
      }),
    ],
    source: ncsu("podocarpus-macrophyllus", "Podocarpus macrophyllus"),
    reviewed: false,
  },
  {
    id: "bach_tuyet_mai",
    nameVi: "Bạch tuyết mai",
    aliases: ["bạch tuyết mai", "bạch tuyết", "mai bạch tuyết", "serissa"],
    scientific: "Serissa japonica",
    match: { species: ["Serissa japonica", "Serissa foetida"], genera: ["Serissa"] },
    group: "bonsai_cay_go",
    basics: {
      lightLevel: "sang_manh",
      light: "Nắng buổi sáng là tốt nhất, che nắng buổi chiều.",
      water: "Giữ đất ẩm đều, không để khô hẳn; đất phải thoát nước tốt.",
      soil: "Đất màu mỡ, thoát nước tốt.",
      toxic: NO_TOXIC_DATA,
      note: "Cây khó tính, thích nhiệt độ ổn định: hạn chế dời chỗ, tránh gió máy lạnh.",
    },
    alohaDoc: null,
    problems: [
      pests({ kinds: ["nhen_do"] }),
      pests({ kinds: ["rep_vay", "rep"], signs: "Thân, cành có vảy nhỏ màu nâu bám chặt; hoặc cành non có đám rệp phủ lớp sáp trắng như bông; lá có thể vàng, dính nhớt." }),
      powderyMildew({ signs: "Lá có lớp bột trắng như phấn hoặc mốc trắng, lá vàng rồi rụng." }),
      thirsty({
        signs: "Lá héo, khô giòn, cành non rũ; đất khô.",
        water: "Giữ đất ẩm đều, kiểm tra hằng ngày vào mùa nắng.",
      }),
    ],
    source: ncsu("serissa-japonica", "Serissa japonica"),
    reviewed: false,
  },
  {
    id: "tac_chanh",
    nameVi: "Tắc (quất) / Chanh",
    aliases: ["cây tắc", "cây quất", "quất", "cây chanh", "chanh", "citrus"],
    scientific: "Citrus spp. (Citrus × microcarpa, Citrus japonica, Citrus limon…)",
    match: { genera: ["Citrus", "Fortunella"] },
    group: "bonsai_cay_go",
    basics: {
      lightLevel: "nang",
      light: "Cần nắng trực tiếp đầy đủ (từ 6 giờ mỗi ngày) để ra hoa, đậu trái.",
      water: "Giữ đất ẩm đều nhưng thoát nước tốt; không để sũng.",
      soil: "Đất màu mỡ, thoát nước tốt.",
      toxic: NO_TOXIC_DATA,
      note: "Cây ra hoa nhiều đợt, có thể vừa có hoa vừa có trái; cần không khí ẩm.",
    },
    alohaDoc: null,
    problems: [
      custom({
        id: "sau_ve_bua",
        condition: "sau_hai",
        title: "Bị sâu vẽ bùa",
        signs: "Lá non có đường ngoằn ngoèo màu bạc bên trong lá, lá quăn queo, biến dạng.",
        summary: "Sâu vẽ bùa đục đường bên trong lá non. Ngắt bỏ lá bị nặng và bảo vệ đợt đọt mới là cây ổn.",
        why: "Sâu non của một loài ngài nhỏ đục bên trong lá non, để lại đường bạc ngoằn ngoèo; lá già ít bị.",
        steps: [
          "Ngắt bỏ lá non bị sâu vẽ bùa nặng, bỏ vào túi kín rồi tiêu huỷ.",
          "Khi cây ra đợt đọt mới, phun chế phẩm trừ sâu sinh học hoặc dầu neem có bán tại Aloha theo hướng dẫn trên bao bì.",
        ],
        care: ["Theo dõi kỹ mỗi đợt cây ra đọt non."],
        severity: "nhe",
      }),
      pests({ kinds: ["nhen_do", "rep_vay", "rep"] }),
      custom({
        id: "muoi_den",
        condition: "nam_benh",
        title: "Lá phủ muội đen như bồ hóng",
        signs: "Mặt lá, cành phủ lớp muội đen như bồ hóng, lau được; thường đi kèm rệp, lá dính nhớt.",
        summary: "Muội đen là nấm mọc trên chất dính do rệp tiết ra. Trị rệp trước, rồi lau sạch muội.",
        why: "Rệp, rệp vảy hút nhựa và tiết ra chất ngọt dính; nấm muội đen mọc trên lớp dính đó làm lá đen, giảm quang hợp.",
        steps: [
          "Tìm và xử lý rệp, rệp vảy trên cây trước (xem mục sâu bọ hút nhựa).",
          "Lau muội đen bằng khăn ẩm hoặc nước xà phòng thật loãng, rồi rửa lại bằng nước sạch.",
        ],
        care: ["Kiểm tra rệp thường xuyên; hết rệp thì muội đen không quay lại."],
        severity: "nhe",
      }),
      rootRot({
        signs: "Lá vàng rụng hàng loạt, gốc thân thâm hoặc chảy nhựa, đất ẩm lâu.",
        dry: "lớp đất mặt đã khô bớt",
      }),
      custom({
        id: "benh_nang",
        condition: "nam_benh",
        title: "Vết loét sần hoặc lá vàng lốm đốm (bệnh nặng)",
        signs: "Lá, cành, trái có vết loét sần màu nâu viền vàng; hoặc lá vàng lốm đốm không đều hai bên gân, trái nhỏ, méo.",
        summary: "Đây có thể là bệnh loét hoặc vàng lá greening, bệnh nặng và dễ lây. Cần nhân viên Aloha xem trực tiếp.",
        why: "Bệnh loét do vi khuẩn, bệnh greening do vi khuẩn lây qua côn trùng; cả hai lây sang cây có múi khác và khó chữa tại nhà.",
        steps: [
          "Để riêng cây ra xa các cây có múi khác.",
          "Cắt bỏ cành, lá, trái có vết loét bằng kéo sạch; bỏ vào túi kín rồi tiêu huỷ, lau kéo bằng cồn sau khi cắt.",
          `Chụp ảnh cận lá và trái, nhắn Zalo hoặc mang cây ra Aloha để được xem trực tiếp. ${BRING}`,
        ],
        care: ["Kiểm tra rệp và côn trùng thường xuyên vì chúng có thể truyền bệnh."],
        severity: "nang",
      }),
    ],
    source: ncsu("citrus-x-microcarpa", "Citrus × microcarpa"),
    reviewed: false,
  },
  {
    id: "lan_ho_diep",
    nameVi: "Lan hồ điệp",
    aliases: ["lan hồ điệp", "hồ điệp", "lan hồ diệp", "phalaenopsis"],
    scientific: "Phalaenopsis spp.",
    match: { genera: ["Phalaenopsis"] },
    group: "khac",
    basics: {
      lightLevel: "tan_xa",
      light: "Ánh sáng nhẹ: bậu cửa sổ hướng đông là tốt nhất; cửa sổ hướng nam, tây thì phải che bớt nắng.",
      water: "Tưới buổi sáng bằng nước ấm vừa, cho nước chảy qua giá thể rồi để ráo hẳn; khoảng 1 lần/tuần, giá thể nên khô bớt giữa hai lần tưới.",
      soil: "Trồng bằng giá thể vỏ thông thoát nước thật tốt, không trồng bằng đất; thay giá thể khoảng 2 năm/lần sau khi hoa tàn.",
      toxic: NO_TOXIC_DATA,
      note: "Hoa tàn thì cắt cành hoa ngay trên mắt đầu tiên bên dưới chỗ hoa tàn; mắt đó có thể ra nhánh hoa mới.",
    },
    alohaDoc: null,
    problems: [
      rootRot({
        signs: "Lá nhăn, mềm dù vẫn tưới đều; rễ nâu đen, nhũn hoặc rỗng; giá thể ẩm lâu, mục.",
        dry: "giá thể đã khô bớt",
        why: "Rễ lan hồ điệp cần thoáng khí. Giá thể sũng nước làm rễ thối; rễ chết thì lá không được nuôi nên nhăn, mềm dù vẫn tưới.",
        extraSteps: ["Rễ khoẻ màu xanh bạc và chắc; rễ thối nâu đen, bóp thấy nhũn hoặc rỗng."],
        severity: "nang",
      }),
      thirsty({
        signs: "Lá nhăn, mềm; rễ trắng bạc, khô, giá thể khô lâu ngày.",
        water: "Tưới khoảng 1 lần/tuần vào buổi sáng, cho nước chảy qua giá thể rồi để ráo hẳn.",
        extraSteps: ["Lá đã nhăn sẽ căng lại dần sau vài lần tưới đều."],
      }),
      custom({
        id: "rung_nu",
        condition: "khac",
        title: "Rụng nụ, hoa mau tàn",
        signs: "Nụ vàng, héo rồi rụng trước khi nở; thường sau khi mua về, đổi chỗ hoặc thay đổi cách tưới, bón phân.",
        summary: "Lan rụng nụ do thay đổi môi trường đột ngột. Giữ chỗ ổn định để các nụ còn lại nở.",
        why: "Lan hồ điệp rụng nụ khi nhiệt độ, độ ẩm, lượng nước, phân bón hoặc chỗ đặt thay đổi đột ngột.",
        steps: [
          "Đặt chậu cố định ở chỗ sáng nhẹ, tránh gió máy lạnh, quạt và nắng chiếu thẳng.",
          "Không xoay, không dời chậu khi đang có nụ.",
          "Giữ lịch tưới và bón phân đều như cũ, không thay đổi đột ngột.",
        ],
        care: ["Giữ chỗ đặt và cách chăm ổn định khi cây đang ra nụ."],
        severity: "nhe",
      }),
      custom({
        id: "dom_hoa",
        condition: "nam_benh",
        title: "Cánh hoa có đốm nhỏ (nấm mốc xám)",
        signs: "Cánh hoa có nhiều đốm nhỏ màu nâu hoặc hồng nhạt, lan dần; hoa mau héo.",
        summary: "Hoa bị nấm mốc xám do ẩm, bí gió. Cắt bỏ hoa bệnh và để thoáng là bệnh dừng lại.",
        why: "Nấm mốc xám (Botrytis) phát triển trên cánh hoa khi không khí ẩm, lạnh và thiếu gió.",
        steps: [
          "Cắt bỏ hoa có đốm, bỏ vào túi kín rồi vứt đi.",
          "Để cây chỗ thoáng gió, không phun nước lên hoa.",
        ],
        care: ["Tưới vào giá thể buổi sáng, không làm ướt hoa."],
        severity: "nhe",
      }),
      pests({ kinds: ["rep_vay", "rep_sap"], noWash: true }),
    ],
    source: ncsu("phalaenopsis", "Phalaenopsis"),
    reviewed: false,
  },
];
