/** Danh mục tỉnh/thành + phường/xã (rút gọn đủ checkout). Phường trống → nhập tay. */

export const VN_PROVINCES: string[] = [
  "An Giang",
  "Bà Rịa - Vũng Tàu",
  "Bạc Liêu",
  "Bắc Giang",
  "Bắc Kạn",
  "Bắc Ninh",
  "Bến Tre",
  "Bình Dương",
  "Bình Định",
  "Bình Phước",
  "Bình Thuận",
  "Cà Mau",
  "Cao Bằng",
  "Cần Thơ",
  "Đà Nẵng",
  "Đắk Lắk",
  "Đắk Nông",
  "Điện Biên",
  "Đồng Nai",
  "Đồng Tháp",
  "Gia Lai",
  "Hà Giang",
  "Hà Nam",
  "Hà Nội",
  "Hà Tĩnh",
  "Hải Dương",
  "Hải Phòng",
  "Hậu Giang",
  "Hòa Bình",
  "Hưng Yên",
  "Khánh Hòa",
  "Kiên Giang",
  "Kon Tum",
  "Lai Châu",
  "Lâm Đồng",
  "Lạng Sơn",
  "Lào Cai",
  "Long An",
  "Nam Định",
  "Nghệ An",
  "Ninh Bình",
  "Ninh Thuận",
  "Phú Thọ",
  "Phú Yên",
  "Quảng Bình",
  "Quảng Nam",
  "Quảng Ngãi",
  "Quảng Ninh",
  "Quảng Trị",
  "Sóc Trăng",
  "Sơn La",
  "Tây Ninh",
  "Thái Bình",
  "Thái Nguyên",
  "Thanh Hóa",
  "Thừa Thiên Huế",
  "Tiền Giang",
  "TP. Hồ Chí Minh",
  "Trà Vinh",
  "Tuyên Quang",
  "Vĩnh Long",
  "Vĩnh Phúc",
  "Yên Bái",
];

/** Phường/xã mẫu cho vài tỉnh hay dùng; tỉnh khác nhập tay. */
export const VN_WARDS: Record<string, string[]> = {
  "TP. Hồ Chí Minh": [
    "Phường Bến Nghé",
    "Phường Đa Kao",
    "Phường Tân Định",
    "Phường 1 (Q.3)",
    "Phường 2 (Q.3)",
    "Phường Võ Thị Sáu",
    "Phường 1 (Q.5)",
    "Phường 15 (Tân Bình)",
    "Phường 1 (Tân Bình)",
    "Phường 4 (Tân Bình)",
    "Phường 7 (Gò Vấp)",
    "Phường 15 (Gò Vấp)",
    "Phường Bình Thạnh",
    "Phường 25 (Bình Thạnh)",
    "Phường Thảo Điền",
    "Phường An Phú",
    "Phường Tân Phú",
    "Xã Bình Chánh",
    "Xã Nhà Bè",
    "Khác (nhập ở ô địa chỉ)",
  ],
  "Hà Nội": [
    "Phường Hàng Bạc",
    "Phường Cửa Nam",
    "Phường Trúc Bạch",
    "Phường Ngọc Hà",
    "Phường Thành Công",
    "Phường Láng Thượng",
    "Phường Trung Hòa",
    "Phường Nhân Chính",
    "Phường Mỹ Đình 1",
    "Phường Cầu Diễn",
    "Khác (nhập ở ô địa chỉ)",
  ],
  "Đà Nẵng": [
    "Phường Hải Châu 1",
    "Phường Thanh Bình",
    "Phường Thạch Thang",
    "Phường Hòa Cường Bắc",
    "Phường Mỹ An",
    "Khác (nhập ở ô địa chỉ)",
  ],
  "Đồng Nai": [
    "Phường Quang Vinh",
    "Phường Tân Phong",
    "Phường Trung Dũng",
    "Xã Long Thành",
    "Khác (nhập ở ô địa chỉ)",
  ],
  "Bình Dương": [
    "Phường Phú Cường",
    "Phường Hiệp Thành",
    "Phường Hòa Phú",
    "Khác (nhập ở ô địa chỉ)",
  ],
};

export function wardsForProvince(province: string): string[] {
  return VN_WARDS[province] || [];
}
